# Generated by Django 5.1.5 on 2025-02-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('word_count', models.IntegerField()),
                ('narrative_structure', models.CharField(max_length=50)),
                ('point_of_view', models.CharField(max_length=50)),
                ('writing_style', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField()),
                ('genre', models.ManyToManyField(related_name='story_genre', to='story.genres')),
                ('theme', models.ManyToManyField(related_name='story_theme', to='story.themes')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.stories')),
            ],
        ),
    ]
