/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Marko Prokopyev (https://sketchfab.com/MarkoProkopyev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-circus-af59cbba6a3249bfb619e1b829964bd7
Title: Flying Circus
*/

import React, { useRef ,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Airplane2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/Airplane2/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=> {
    console.log(actions);
    // actions.Dynamic_pose.play();
  })
    
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="941b2da95bd54e61b701f8902ef2ed20fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="plane_body" position={[-318.81, 331.09, -1.72]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="aileron_left" position={[4.63, -3.46, -1.17]}>
                    <group name="outline001" position={[-1.44, 3.44, 0.45]} rotation={[0, 1.57, 0]}>
                      <mesh name="outline001_M_outline_0" geometry={nodes.outline001_M_outline_0.geometry} material={materials.M_outline} />
                    </group>
                    <mesh name="aileron_left_M_plane_0" geometry={nodes.aileron_left_M_plane_0.geometry} material={materials.M_plane} />
                  </group>
                  <group name="aileron_right" position={[4.39, 3.1, -1.2]}>
                    <group name="outline002" position={[-1.2, -3.12, 0.48]} rotation={[0, 1.57, 0]}>
                      <mesh name="outline002_M_outline_0" geometry={nodes.outline002_M_outline_0.geometry} material={materials.M_outline} />
                    </group>
                    <mesh name="aileron_right_M_plane_0" geometry={nodes.aileron_right_M_plane_0.geometry} material={materials.M_plane} />
                  </group>
                  <group name="Armature" position={[8.42, -0.03, -0.11]} rotation={[0, 1.57, 0]}>
                    <group name="Object_17">
                      <group name="_rootJoint">
                        <group name="Bone_00" rotation={[Math.PI / 2, 0, 0]}>
                          <group name="Bone_end_07" position={[0, 1, 0]} />
                          <group name="plane_final002" position={[0, 0, -0.9]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                            <mesh name="plane_final002_M_plane_0" geometry={nodes.plane_final002_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="plane_final003" position={[0, 0, 0.88]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                            <mesh name="plane_final003_M_plane_0" geometry={nodes.plane_final003_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="outline004" position={[0.6, -5.24, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh name="outline004_M_outline_0" geometry={nodes.outline004_M_outline_0.geometry} material={materials.M_outline} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Armature001" position={[8.44, -0.04, 1.45]} rotation={[0, 0, 0.04]}>
                    <group name="Object_28">
                      <group name="_rootJoint_1">
                        <group name="Bone_01" rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                          <group name="Bone_end_08" position={[0, 1, 0]} />
                          <group name="plane_final001" position={[0.31, 0.21, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                            <mesh name="plane_final001_M_plane_0" geometry={nodes.plane_final001_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="outline003" position={[2.17, -5.24, -0.21]} rotation={[-1.53, 0, 0]}>
                            <mesh name="outline003_M_outline_0" geometry={nodes.outline003_M_outline_0.geometry} material={materials.M_outline} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Armature003" position={[1.98, 0.99, -0.51]} rotation={[-2.13, 0.39, -0.03]}>
                    <group name="Object_37">
                      <group name="_rootJoint_2">
                        <group name="Bone_02" rotation={[Math.PI / 2, 0, 0]}>
                          <group name="Bone_end_09" position={[0, 1, 0]} />
                          <group name="exhaust_right_top" position={[0.01, 0.36, -0.21]} rotation={[0.53, 0.22, 0.32]}>
                            <mesh name="exhaust_right_top_M_plane_0" geometry={nodes.exhaust_right_top_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="outline008" position={[1.38, -0.24, -0.74]} rotation={[-1.64, 1.18, 2.2]}>
                            <mesh name="outline008_M_outline_0" geometry={nodes.outline008_M_outline_0.geometry} material={materials.M_outline} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Armature004" position={[1.98, 0.76, -0.85]} rotation={[-2.26, 0.39, 0.02]}>
                    <group name="Object_46">
                      <group name="_rootJoint_3">
                        <group name="Bone_03" rotation={[Math.PI / 2, 0, 0]}>
                          <group name="Bone_end_010" position={[0, 1, 0]} />
                          <group name="exhaust_right_bot" position={[0.01, 0.35, 0.24]} rotation={[0.64, 0.22, 0.32]}>
                            <mesh name="exhaust_right_bot_M_plane_0" geometry={nodes.exhaust_right_bot_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="outline009" position={[1.38, -0.18, -0.36]} rotation={[-1.52, 1.18, 2.2]}>
                            <mesh name="outline009_M_outline_0" geometry={nodes.outline009_M_outline_0.geometry} material={materials.M_outline} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Armature002" position={[1.98, -0.98, -0.51]} rotation={[-1.01, -0.39, 3.12]} scale={-1}>
                    <group name="Object_55">
                      <group name="_rootJoint_4">
                        <group name="Bone_04" rotation={[Math.PI / 2, 0, 0]}>
                          <group name="Bone_end_011" position={[0, 1, 0]} />
                          <group name="exhaust_left_top" position={[-0.01, 0.39, -0.19]} rotation={[-2.62, -0.22, 2.82]} scale={-1}>
                            <mesh name="exhaust_left_top_M_plane_0" geometry={nodes.exhaust_left_top_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="outline006" position={[1.37, -0.21, -0.72]} rotation={[1.51, -1.18, 0.94]} scale={-1}>
                            <mesh name="outline006_M_outline_0" geometry={nodes.outline006_M_outline_0.geometry} material={materials.M_outline} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Armature005" position={[1.98, -0.83, -0.85]} rotation={[-0.88, -0.39, -3.12]} scale={-1}>
                    <group name="Object_64">
                      <group name="_rootJoint_5">
                        <group name="Bone_05" rotation={[Math.PI / 2, 0, 0]}>
                          <group name="Bone_end_012" position={[0, 1, 0]} />
                          <group name="exhaust_left_bot" position={[0.02, 0.33, 0.21]} rotation={[-2.49, -0.22, 2.82]} scale={-1}>
                            <mesh name="exhaust_left_bot_M_plane_0" geometry={nodes.exhaust_left_bot_M_plane_0.geometry} material={materials.M_plane} />
                          </group>
                          <group name="outline007" position={[1.39, -0.21, -0.38]} rotation={[1.63, -1.18, 0.94]} scale={-1}>
                            <mesh name="outline007_M_outline_0" geometry={nodes.outline007_M_outline_0.geometry} material={materials.M_outline} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="Armature006" position={[3.76, -4.7, -0.75]} rotation={[0, -0.08, 0]}>
                    <group name="Object_73">
                      <group name="_rootJoint_6">
                        <group name="Bone_06" rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
                          <group name="Bone_end_013" position={[0, 1, 0]} />
                          <group name="trail" rotation={[-Math.PI / 2, -Math.PI / 2, 0]}>
                            <mesh name="trail_M_vfx_0" geometry={nodes.trail_M_vfx_0.geometry} material={materials.M_vfx} />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="smoke" position={[2.67, -1.53, -0.85]} scale={0}>
                    <mesh name="smoke_M_vfx_0" geometry={nodes.smoke_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke001" position={[2.67, -1.53, -0.85]} scale={0}>
                    <mesh name="smoke001_M_vfx_0" geometry={nodes.smoke001_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke002" position={[2.83, -1.52, -0.4]} rotation={[0.84, 0.14, -1.51]} scale={0.95}>
                    <mesh name="smoke002_M_vfx_0" geometry={nodes.smoke002_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke003" position={[7.58, -1.53, -0.74]} rotation={[0.72, 0.18, -1.94]} scale={1.28}>
                    <mesh name="smoke003_M_vfx_0" geometry={nodes.smoke003_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke004" position={[6.89, -1.53, -0.67]} rotation={[0.6, -0.26, 1.62]} scale={0.38}>
                    <mesh name="smoke004_M_vfx_0" geometry={nodes.smoke004_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke005" position={[7.84, -1.53, -0.85]} rotation={[0.88, -0.44, 1.29]} scale={0.02}>
                    <mesh name="smoke005_M_vfx_0" geometry={nodes.smoke005_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke006" position={[7.58, 1.29, -0.74]} rotation={[-0.72, -0.17, 1.2]} scale={1.28}>
                    <mesh name="smoke006_M_vfx_0" geometry={nodes.smoke006_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke007" position={[2.67, 1.29, -0.85]} scale={0}>
                    <mesh name="smoke007_M_vfx_0" geometry={nodes.smoke007_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke008" position={[2.67, 1.29, -0.85]} scale={0}>
                    <mesh name="smoke008_M_vfx_0" geometry={nodes.smoke008_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke009" position={[2.83, 1.3, -0.4]} rotation={[-0.84, -0.14, 1.64]} scale={0.95}>
                    <mesh name="smoke009_M_vfx_0" geometry={nodes.smoke009_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke010" position={[6.89, 1.29, -0.67]} rotation={[-0.6, 0.26, -1.52]} scale={0.38}>
                    <mesh name="smoke010_M_vfx_0" geometry={nodes.smoke010_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="smoke011" position={[7.84, 1.29, -0.85]} rotation={[-0.88, 0.44, -1.85]} scale={0.02}>
                    <mesh name="smoke011_M_vfx_0" geometry={nodes.smoke011_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="outline" position={[3.19, -0.02, -0.71]} rotation={[0, 1.57, 0]}>
                    <mesh name="outline_M_outline_0" geometry={nodes.outline_M_outline_0.geometry} material={materials.M_outline} />
                  </group>
                  <mesh name="plane_body_M_plane_0" geometry={nodes.plane_body_M_plane_0.geometry} material={materials.M_plane} />
                </group>
                <group name="propeller" position={[-318.81, 331.09, -1.72]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="fx" position={[0.1, -0.01, 0]} rotation={[0, Math.PI / 2, 0]} scale={2.27}>
                    <mesh name="fx_M_vfx_0" geometry={nodes.fx_M_vfx_0.geometry} material={materials.M_vfx} />
                  </group>
                  <group name="outline005" position={[3.19, -0.02, -0.71]} rotation={[0, 1.57, 0]}>
                    <mesh name="outline005_M_outline_0" geometry={nodes.outline005_M_outline_0.geometry} material={materials.M_outline} />
                  </group>
                  <mesh name="propeller_M_plane_0" geometry={nodes.propeller_M_plane_0.geometry} material={materials.M_plane} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/Airplane2/scene-transformed.glb')
